apiVersion: apps/v1
kind: Deployment
metadata:
  name: number-generator
  labels:
    app: number-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: number-generator
  template:
    metadata:
      labels:
        app: number-generator
    spec:
      containers:
        - name: number-generator
          image: a1:32000/numbergenerator:1.4
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: PRIME_DECOMPOSITION_URL
              value: http://prime-decomposition
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "50m"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 20
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: number-generator
  labels:
    app: number-generator
spec:
  selector:
    app: number-generator
  ports:
    - name: "80"
      port: 80
      targetPort: 80
