apiVersion: apps/v1
kind: Deployment
metadata:
  name: number-generator
  labels:
    app: number-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: number-generator
  template:
    metadata:
      labels:
        app: number-generator
    spec:
      containers:
        - name: number-generator
          image: number-generator
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: PRIME_DECOMPOSITION_URL
              value: http://prime-decomposition
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "50m"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 20
            timeoutSeconds: 2
            periodSeconds: 10
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: number-generator
  labels:
    app: number-generator
spec:
  type: NodePort
  selector:
    app: number-generator
  ports:
    - name: "8080"
      port: 80
      targetPort: 80
      nodePort: 30000
