apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-decomposition-ui
  labels:
    app: prime-decomposition-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prime-decomposition-ui
  template:
    metadata:
      labels:
        app: prime-decomposition-ui
    spec:
      containers:
        - name: prime-decomposition-ui
          image: a1:32000/primedecompositionui:1.5
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: NUMBER_GENERATOR_URL
              value: http://number-generator
          resources:
            limits:
              memory: "512Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "50m"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 120
            timeoutSeconds: 30
            periodSeconds: 60
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 4
---
apiVersion: v1
kind: Service
metadata:
  name: prime-decomposition-ui
  labels:
    app: prime-decomposition-ui
spec:
  type: NodePort
  selector:
    app: prime-decomposition-ui
  ports:
    - name: "80"
      port: 80
      targetPort: 80
      nodePort: 30000
